version: '3.9'
services:
  db:
    image: mysql:latest
    container_name: knowledge-db
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_DATABASE: 'knowledge'
